color: blue
fieldLayouts:
  7c088e3d-5ca5-419f-a68a-668195c76ba8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c032f30f-b0d5-4b5c-a335-1a37dfbcb11d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c9156a4-4721-477d-abe0-aa698055dfe5
        userCondition: null
handle: hero
hasTitleField: true
icon: cubes
name: Hero
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
