altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  3b449633-0f76-4394-9314-8c7748951f3d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e3e8a09c-f959-47ee-a13c-175634a0af28
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5686fc27-341b-4959-8df8-3e9cc335168a
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
