defaultPlacement: end
enableVersioning: true
entryTypes:
  - 111d2d01-deb5-4542-a346-a475708f3f90 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9d422645-22d6-4617-af7b-2055c66fdbc4: # Azure Website
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
